on: push
jobs:
  deploy:
    name: List S3 Buckets
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::828692096705:role/github-action-oid-role
        aws-region: us-east-1

    - name: List S3 Buckets with the AWS CLI
      run: |
        aws s3 ls
